### ISSUE TITLE
Failed to get Tx data

### ISSUE THREAD

**Issue by kidinamoto01** [wolfposd/TMChat#2]
Hello, 

I went into some trouble when i tried to run the TMChat project.  It failed to get Json object from byte[].

```
 @Override
    public ResponseDeliverTx receivedDeliverTx(RequestDeliverTx req) {

        Message msg = gson.fromJson(new String(req.getTx().toByteArray()), Message.class);

        System.out.println(msg);

        FrontendListener l = frontends.get(msg.receiver);
        if (l != null) {
            l.messageIncoming(msg);
        }

        return ResponseDeliverTx.newBuilder().setCode(CodeType.OK).build();
    }
```
Error info is;

Exception in thread "SocketThread -Consensus" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at com.github.wolfposd.tmchat.NodeCommunication.receivedDeliverTx(NodeCommunication.java:123)
	at com.github.jtendermint.jabci.socket.ASocket.handleRequest(ASocket.java:112)
	at com.github.jtendermint.jabci.socket.TSocket$SocketHandler.run(TSocket.java:222)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 7 more

is there a better way to convert the object?

Thank you so much.

**Comment by wolfposd** [comment]
this might be due to the change of the json-rpc interface
it now expects Base64 and not Base16 anymore

havent come around to updating this yet

**Comment by kidinamoto01** [comment]
@wolfposd 
Hey,
I tried not use the RPC API , and send HTTP request to send messages to the Tendermint core. And it worked. 
It seems there's some bug with  json-rpc.

**Comment by wolfposd** [comment]
updated the websocket library to use base64, should work now
