### ISSUE TITLE
Cannot connect to Websocket

### ISSUE THREAD

**Issue by sparkspeedy** [wolfposd/TMChat#4]
I am trying to run the TMChat application. I start the tendermint using 'tendermint node' and then initiate the TMChat using the following command:

`root@kali:~/TMChat/target# java -jar TMChat-0.0.1-SNAPSHOT.jar left right`

The application connects to tendermint and I can see the blocks being generated. The left and right windows open but as soon as I send a message, the following error occurs:

```
root@kali:~/TMChat/target# sudo java -jar TMChat-0.0.1-SNAPSHOT.jar left right
Started TMSP Socket
waiting 5 seconds before connecting to Websocket...
Trying to connect to Websocket...

Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
    at com.github.jtmsp.websocket.Websocket.sendMessage(Websocket.java:170)
    at com.github.wolfposd.tmchat.NodeCommunication.sendMessage(NodeCommunication.java:123)
    at com.github.wolfposd.tmchat.frontend.Frontend.sendButtonPressed(Frontend.java:102)
    at com.github.wolfposd.tmchat.frontend.Frontend.lambda$setupUI$0(Frontend.java:84)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6533)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


```
How can I solve the issue?

**Comment by Alcereo** [comment]
I've soled this issue by reimplementing the `com.github.jtmsp.websocket.Websocket` class with `org.java-websocket` in `com.github.jTendermint:websocket` library. I wrote about it in [this issue](https://github.com/jTendermint/websocket/issues/4).

**Comment by wolfposd** [comment]
ive just updated all the components in tmchat, but nevertheless i am not experiencing any issues with the websocket implementation (glassfish)
